=== chaijewon/2022-07-20-JSPStudy/MyBatisProject2/src/main/webapp/xml/sawon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
     <sawon>
       <list>
         <name></name>
         <dept></dept>
         <tel></tel>
       </list>
       <list>
         <name></name>
         <dept></dept>
         <phone></phone>
       </list>
     </sawon>
     &nbsp; 
     <!ENTITY nbsp " ">
     => &nbsp;
     <!ATTLIST list no ID>
 -->
 <!ELEMENT sawon (list+)>
 <!ELEMENT list (name,dept,(tel|phone))>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT dept (#PCDATA)>
 <!ELEMENT tel (#PCDATA)>
 <!ELEMENT phone (#PCDATA)>

=== chaijewon/2022-07-20-JSPStudy/MyBatisProject2/src/main/webapp/xml/sawon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sawon SYSTEM "sawon.dtd">
<sawon>
  <list>
    <name>aaa</name>
    <dept>aaa</dept>
    <tel>aaa</tel>
  </list>
  <list>
    <name>bbb</name>
    <dept>bbb</dept>
    <tel>bbb</tel>
  </list>
</sawon>
